const purposesTableOne = [
	['Bostad', 'Småhus', 'Friliggande enbostadshus'],
	['Bostad', 'Småhus', 'Kedjehus'],
	['Bostad', 'Småhus', 'Radhus'],
	['Bostad', 'Småhus', 'Parhus'],
	['Bostad', 'Småhus', 'Friliggande tvåbostadshus'],
	['Bostad', 'Småhus', 'Komplementbostadshus'],
	['Bostad', 'Småhus', 'Ytterligare bostad i enbostadshus'],
	['Bostad', 'Småhus', 'Okänd'],
	['Bostad', 'Flerbostadshus', 'Flerbostadshus'],
	['Bostad', 'Flerbostadshus', 'Okänd'],
	['Bostad', 'Specialbostad', 'Specialbostadshus för äldre'],
	['Bostad', 'Specialbostad', 'Specialbostadshus för funktionsnedsatta'],
	['Bostad', 'Specialbostad', 'Specialbostadshus för studenter'],
	['Bostad', 'Specialbostad', 'Specialbostadshus för unga'],
	['Bostad', 'Specialbostad', 'Okänd'],
	['Bostad', 'Bostadskomplement', 'Komplementbyggnad, utan mänsklig aktivitet'],
	['Bostad', 'Bostadskomplement', 'Komplementbyggnad, mänsklig aktivitet'],
	['Bostad', 'Bostadskomplement', 'Carport'],
	['Bostad', 'Bostadskomplement', 'Garage'],
	['Bostad', 'Bostadskomplement', 'Miljöhus'],
	['Bostad', 'Bostadskomplement', 'Uterum'],
	['Bostad', 'Bostadskomplement', 'Cykelförvaring'],
	['Bostad', 'Bostadskomplement', 'Sjöbod'],
	['Bostad', 'Bostadskomplement', 'Teknisk försörjning'],
	['Bostad', 'Bostadskomplement', 'Okänd'],
	['Bostad', 'Okänd', 'Okänd'],
];

const purposesTableTwo = [
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Resecentrum'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Järnvägsstation'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Busstation'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Flygterminal'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Färjeterminal'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Lokstall'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Hangar'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Bussgarage'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Fyrbyggnad'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Väderskydd för kollektivtrafik'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Parkeringshus'],
	['Samhällsfunktion', 'Trafik och Kommunikation', 'Okänd'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Lager'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Miljöhus'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Cykelförvaring'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Garage'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Skärmtak'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Förråd'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Carport'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Offentlig toalett'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Teknisk försörjning'],
	['Samhällsfunktion', 'Samhällsfunktionskomplement', 'Okänd'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Kommunal förvaltning'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Regional förvaltning'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Statlig förvaltning'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Polisstation'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Räddningstjänst'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Arkiv'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Kriminalvård'],
	['Samhällsfunktion', 'Offentlig förvaltning', 'Okänd'],
	['Samhällsfunktion', 'Utbildning', 'Förskola'],
	['Samhällsfunktion', 'Utbildning', 'Grundskola'],
	['Samhällsfunktion', 'Utbildning', 'Gymnasium'],
	['Samhällsfunktion', 'Utbildning', 'Högskola/universitet'],
	//  Page 3
	['Samhällsfunktion', 'Utbildning', 'Övrig utbildning'],
	['Samhällsfunktion', 'Utbildning', 'Okänd'],
	['Samhällsfunktion', 'Kultur', 'Museum'],
	['Samhällsfunktion', 'Kultur', 'Bibliotek'],
	['Samhällsfunktion', 'Kultur', 'Konserthus'],
	['Samhällsfunktion', 'Kultur', 'Teater'],
	['Samhällsfunktion', 'Kultur', 'Biograf'],
	['Samhällsfunktion', 'Kultur', 'Hembygdsgård'],
	['Samhällsfunktion', 'Kultur', 'Samlingslokal'],
	['Samhällsfunktion', 'Kultur', 'Okänd'],
	['Samhällsfunktion', 'Idrott', 'Badhus'],
	['Samhällsfunktion', 'Idrott', 'Multiarena'],
	['Samhällsfunktion', 'Idrott', 'Ridhus'],
	['Samhällsfunktion', 'Idrott', 'Sporthall'],
	['Samhällsfunktion', 'Idrott', 'Ishall'],
	['Samhällsfunktion', 'Idrott', 'Komplement till idrottsanläggning'],
	['Samhällsfunktion', 'Idrott', 'Okänd'],
	['Samhällsfunktion', 'Hälsa och sjukvård', 'Vård- och omsorgsboende'],
	['Samhällsfunktion', 'Hälsa och sjukvård', 'Sjukhus'],
	['Samhällsfunktion', 'Hälsa och sjukvård', 'Primärvård'],
	['Samhällsfunktion', 'Hälsa och sjukvård', 'Tandvård'],
	['Samhällsfunktion', 'Hälsa och sjukvård', 'Djurklinik'],
	['Samhällsfunktion', 'Hälsa och sjukvård', 'Djursjukhus'],
	['Samhällsfunktion', 'Hälsa och sjukvård', 'Okänd'],
	['Samhällsfunktion', 'Samfund', 'Samfund'],
	['Samhällsfunktion', 'Samfund', 'Krematorium'],
	['Samhällsfunktion', 'Samfund', 'Okänd'],
	['Samhällsfunktion', 'Teknisk försörjning', 'Okänd '],
	['Samhällsfunktion', 'Okänd', 'Okänd'],
];

const purposesTableThree = [
	['Verksamhet', 'Logi och restaurang', 'Hotell'],
	['Verksamhet', 'Logi och restaurang', 'Vandrarhem'],
	['Verksamhet', 'Logi och restaurang', 'Härbärge'],
	['Verksamhet', 'Logi och restaurang', 'Servicebyggnad'],
	['Verksamhet', 'Logi och restaurang', 'Stuga'],
	['Verksamhet', 'Logi och restaurang', 'Pensionat'],
	['Verksamhet', 'Logi och restaurang', 'Konferens'],
	['Verksamhet', 'Logi och restaurang', 'Restaurang'],
	['Verksamhet', 'Logi och restaurang', 'Okänd'],
	['Verksamhet', 'Kontor', 'Kontor'],
	['Verksamhet', 'Kontor', 'Okänd'],
	['Verksamhet', 'Handel', 'Drivmedel'],
	['Verksamhet', 'Handel', 'Fordonstvätt'],
	['Verksamhet', 'Handel', 'Partihandel'],
	['Verksamhet', 'Handel', 'Köpcentrum'],
	['Verksamhet', 'Handel', 'Detaljhandel livsmedel'],
	['Verksamhet', 'Handel', 'Detaljhandel med skrymmande varor'],
	['Verksamhet', 'Handel', 'Detaljhandel utom livsmedel'],
	['Verksamhet', 'Handel', 'Detaljhandel utom skrymmande varor'],
	['Verksamhet', 'Handel', 'Detaljhandel utom livsmedel eller skrymmande varor'],
	['Verksamhet', 'Handel', 'Mässhall'],
	['Verksamhet', 'Handel', 'Okänd'],
	['Verksamhet', 'Verksamhetskomplement', 'Lager'],
	['Verksamhet', 'Verksamhetskomplement', 'Miljöhus'],
	['Verksamhet', 'Verksamhetskomplement', 'Cykelförvaring'],
	['Verksamhet', 'Verksamhetskomplement', 'Garage'],
	['Verksamhet', 'Verksamhetskomplement', 'Kundvagnsparkering'],
	['Verksamhet', 'Verksamhetskomplement', 'Skärmtak'],
	['Verksamhet', 'Verksamhetskomplement', 'Förråd'],
	['Verksamhet', 'Verksamhetskomplement', 'Teknisk försörjning'],
	['Verksamhet', 'Verksamhetskomplement', 'Okänd'],
	['Verksamhet', 'Okänd', 'Okänd'],
];

const purposesTableFour = [
	// EDIT: Note that Industri in Nivå 2 has been changed to Generell Industri to not interfer with
	// the purpose in Nivå 1 (property names must be globally unique).
	['Industri', 'Energiförsörjning', 'Energiförsörjning'],
	['Industri', 'Generell Industri', 'Tillverkning'],
	['Industri', 'Generell Industri', 'Cistern'],
	['Industri', 'Generell Industri', 'Silo'],
	['Industri', 'Generell Industri', 'Kylhus'],
	['Industri', 'Generell Industri', 'Lager'],
	['Industri', 'Generell Industri', 'Lastkaj'],
	['Industri', 'Generell Industri', 'Okänd'],
	['Industri', 'Industrikomplement', 'Miljöhus'],
	['Industri', 'Industrikomplement', 'Cykelförvaring'],
	['Industri', 'Industrikomplement', 'Garage'],
	['Industri', 'Industrikomplement', 'Skärmtak'],
	['Industri', 'Industrikomplement', 'Förråd'],
	['Industri', 'Industrikomplement', 'Teknisk försörjning'],
	['Industri', 'Industrikomplement', 'Okänd'],
	['Industri', 'Okänd', 'Okänd'],
];

const purposesTableFive = [
	['Lantbruk', 'Silo', 'Silo'],
	['Lantbruk', 'Maskinhall', 'Maskinhall'],
	['Lantbruk', 'Cistern', 'Cistern'],
	['Lantbruk', 'Fiske', 'Båthus'],
	['Lantbruk', 'Fiske', 'Redskapsbod'],
	['Lantbruk', 'Renskötsel', 'Renvaktarstuga'],
	['Lantbruk', 'Växthus', 'Växthus'],
	['Lantbruk', 'Djurstall', 'Djurstall'],
	['Lantbruk', 'Lantbrukskomplement', 'Lager'],
	['Lantbruk', 'Lantbrukskomplement', 'Miljöhus'],
	['Lantbruk', 'Lantbrukskomplement', 'Cykelförvaring'],
	['Lantbruk', 'Lantbrukskomplement', 'Garage'],
	['Lantbruk', 'Lantbrukskomplement', 'Skärmtak'],
	['Lantbruk', 'Lantbrukskomplement', 'Förråd'],
	['Lantbruk', 'Lantbrukskomplement', 'Teknisk försörjning'],
	['Lantbruk', 'Lantbrukskomplement', 'Okänd'],
	['Lantbruk', 'Okänd', 'Okänd'],
];

const purposesTableSix = [
	['Övriga byggnadsverk', 'Jordkällare', 'Jordkällare'],
	['Övriga byggnadsverk', 'Friluftsbyggnad', 'Vindskydd'],
	['Övriga byggnadsverk', 'Friluftsbyggnad', 'Värmestuga, Raststuga'],
	['Övriga byggnadsverk', 'Kolonistuga', 'Kolonistuga'],
	['Övriga byggnadsverk', 'Fritidsbyggnad', 'Sjöbod'],
	['Övriga byggnadsverk', 'Fritidsbyggnad', 'Fäbod'],
	['Övriga byggnadsverk', 'Fritidsbyggnad', 'Jaktstuga'],
	['Övriga byggnadsverk', 'Byggnadsverk', 'Plank'],
	['Övriga byggnadsverk', 'Byggnadsverk', 'Mur'],
	['Övriga byggnadsverk', 'Byggnadsverk', 'Mast'],
	['Övriga byggnadsverk', 'Byggnadsverk', 'Torn'],
	['Övriga byggnadsverk', 'Okänd', 'Okänd'],
];

export default [
	...purposesTableOne,
	...purposesTableTwo,
	...purposesTableThree,
	...purposesTableFour,
	...purposesTableFive,
	...purposesTableSix,
];
